
pull_request_rules:
  - name: Merge Queue
    conditions: []
    actions:
      queue:
queue_rules:
  - name: default
    update_method: rebase
    merge_method: rebase
    queue_conditions:
      - label = dependencies
      - check-success = check-flake
      - check-success ~= build-home-nix-system
      - check-success ~= build-home-nix-home
      - check-success ~= build-nixps-system
      - check-success ~= build-home-nixps-home
      - base = master
    merge_conditions: []
